name: _
publish_to: none
environment:
  sdk: ^3.8.0
workspace:
  - packages/alsa_midi_linux
  - packages/midi_device
  - packages/midi_device_alsa_linux
  - example/midi_device_example
  - packages/midi_device_flutter_command

